module.exports = {
    USER_REGISTERED: 'User registered successfully.',
    USER_NOT_REGISTERED: 'User registration failed.',
    LOGIN_SUCCESS: 'Login successful.',
    USER_FETCHED: 'User fetched successfully.',
    USER_UPDATED: 'User updated successfully.',
    USER_NOT_FOUND: 'User not found.',
    USER_ROLE_UPDATED: 'User role updated successfully.',
    USER_STATUS_UPDATED: 'User status updated successfully.',
    USER_DELETED: 'User deleted successfully.',
    USER_NOT_EXISTS: 'User does not exist.',
    USER_DISABLED: 'User account is disabled.',
    USER_EXISTS: 'User already exists.',
    ADDRESS_CREATED: 'Address created successfully',
    ADDRESS_LIST: 'Address list fetched successfully',
    ADDRESS_NOT_FOUND: 'Address not found',
    ADDRESS_UPDATED: 'Address updated successfully',
    ADDRESS_DELETED: 'Address deleted successfully',
    USERS_FETCHED: 'Users fetched successfully.',
    ROLE_NOT_FOUND: 'Role not found.',
    INVALID_CREDS: 'Invalid email or password.',
    SERVER_ERROR: 'Something went wrong. Please try again later',
    PRODUCT_CREATED: 'Product created successfully.',
    PRODUCT_NOT_CREATED: 'Product could not be created.',
    PRODUCT_LIST: 'Products fetched successfully.',
    PRODUCT_FETCHED: 'Product details fetched successfully.',
    PRODUCT_NOT_FOUND: 'Product not found.',
    PRODUCT_UPDATED: 'Product updated successfully.',
    PRODUCT_DELETED: 'Product deleted successfully.',
    ITEM_ADDED_TO_CART: 'Item added to cart successfully.',
    CART_FETCHED: 'Cart fetched successfully.',
    CART_EMPTY: 'Cart is empty.',
    CART_UPDATED: 'Cart updated successfully.',
    CART_ITEM_NOT_FOUND: 'Cart item not found.',
    INVALID_QUANTITY: 'Invalid quantity provided.',
    OUT_OF_STOCK: 'Product is out of stock.',
    CATEGORY_CREATED: 'Category created successfully.',
    CATEGORY_LIST: 'Categories fetched successfully.',
    CATEGORY_UPDATED: 'Category updated successfully.',
    CATEGORY_DELETED: 'Category deleted successfully.',
    CATEGORY_NOT_FOUND: 'Category not found.',
    INVENTORY_UPDATED: 'Inventory updated successfully.',
    INVENTORY_FETCHED: 'Inventory fetched successfully.',
    INVENTORY_NOT_FOUND: 'Inventory not found.',
    VARIANT_NOT_FOUND: 'Product variant not found.',
    ORDER_PLACED: 'Order placed successfully.',
    ORDERS_FETCHED: 'Orders fetched successfully.',
    ORDER_FETCHED: 'Order details fetched successfully.',
    ORDER_NOT_FOUND: 'Order not found.',
    VENDOR_ORDERS_FETCHED: 'Vendor orders fetched successfully.',
    ORDER_STATUS_UPDATED: 'Order status updated successfully.',
    INVALID_STATUS_CHANGE: 'Invalid order status change.',
    NOT_ALLOWED: 'You are not allowed to perform this action.',
    VARIANT_CREATED: 'Product variant created successfully.',
    SKU_ALREADY_EXISTS: 'SKU already exists.',
};